### ISSUE TITLE
TabNam Error

### ISSUE THREAD

**Issue by anonymous34** [data2health/DQe-c-v2#33]
Hello, when I run this:

`python DQe-c.py -c C:\DQe-c-v2\configs\config.json
`
I got error:

```
Database connection established
Traceback (most recent call last):
  File "DQe-c.py", line 131, in <module>
    main(config_file, vis_opt)
  File "DQe-c.py", line 42, in main
    Diff(query).createDifference()
  File "C:\DQe-c-v2\modules\diff.py", line 22, in createDifference
    DQTBL = self.query.DQTBL.merge(DB_TBLs, on=["TabNam", "ColNam"], how="left")
  File "C:\Anaconda2\envs\env3.5\lib\site-packages\pandas\core\frame.py", line 7334, in merge
    validate=validate,
  File "C:\Anaconda2\envs\env3.5\lib\site-packages\pandas\core\reshape\merge.py", line 81, in merge
    validate=validate,
  File "C:\Anaconda2\envs\env3.5\lib\site-packages\pandas\core\reshape\merge.py", line 626, in __init__
    ) = self._get_merge_keys()
  File "C:\Anaconda2\envs\env3.5\lib\site-packages\pandas\core\reshape\merge.py", line 988, in _get_merge_keys
    left_keys.append(left._get_label_or_level_values(lk))
  File "C:\Anaconda2\envs\env3.5\lib\site-packages\pandas\core\generic.py", line 1774, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'TabNam'
```

**Comment by liquidcarbon** [comment]
It appears that they wrote 'colnam' in the PGSQL query, but they are trying to join (merge) on 'ColNam'.  https://github.com/data2health/DQe-c-v2/blob/master/modules/diff.py#L118  Since everything is case-sensitive in Python you're getting a KeyError.
